{
 "title": "Ingress by Host",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "glueops_captain_domain", "label": "glueops_captain_domain", "query": { "query": "label_values(captain_domain)" } },
   { "name": "glueops_prometheus_replica", "label": "glueops_prometheus_replica", "query": { "query": "label_values(__replica__)" } },
   {
    "name": "host",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "Top User Agents",
   "type": "table",
   "gridPos": { "h": 17, "w": 7, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "topk(10, sum by (http_user_agent) (count_over_time({captain_domain=\"$glueops_captain_domain\",__replica__=\"$glueops_prometheus_replica\",app=\"ingress-nginx\", glueops_job_name=\"nginx-with-host\", http_host = \"$host\"} | json |  __error__=\"\" [$__interval])))"
    }
   ]
  },
  {
   "title": "Top Requested Paths",
   "type": "table",
   "gridPos": { "h": 17, "w": 10, "x": 7, "y": 0 },
   "targets": [
    {
     "expr": "topk(10, sum by (uri) (count_over_time({captain_domain=\"$glueops_captain_domain\",__replica__=\"$glueops_prometheus_replica\",app=\"ingress-nginx\", glueops_job_name=\"nginx-with-host\", http_host = \"$host\"} | json |  __error__=\"\" [$__interval])))"
    }
   ]
  },
  {
   "title": "Top IPs",
   "type": "table",
   "gridPos": { "h": 17, "w": 7, "x": 17, "y": 0 },
   "targets": [
    {
     "expr": "topk(10, sum by (remote_addr) (count_over_time({captain_domain=\"$glueops_captain_domain\",__replica__=\"$glueops_prometheus_replica\",app=\"ingress-nginx\", glueops_job_name=\"nginx-with-host\", http_host = \"$host\"} | json |  __error__=\"\" [$__interval])))"
    }
   ]
  },
  {
   "title": "Count by Response Codes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "topk(10, sum by (status) (count_over_time({captain_domain=\"$glueops_captain_domain\",__replica__=\"$glueops_prometheus_replica\",app=\"ingress-nginx\", glueops_job_name=\"nginx-with-host\", http_host = \"$host\"} | json |  __error__=\"\" [$__interval])))",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "95th percentile of Request Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "quantile_over_time(0.95,{captain_domain=\"$glueops_captain_domain\",__replica__=\"$glueops_prometheus_replica\",app=\"ingress-nginx\", glueops_job_name=\"nginx-with-host\", http_host = \"$host\"} | json | unwrap request_time |  __error__=\"\"  [$__interval]) by (http_host)",
     "legendFormat": "{{status}}"
    }
   ]
  }
 ]
}