{
 "title": "DevOps - External-dns",
 "description": "Grafana dashboard to display external-dns metrics",
 "tags": [
  "external-dns",
  "dns"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "glueops_captain_domain", "label": "glueops_captain_domain", "query": { "query": "label_values(captain_domain)" } },
   { "name": "glueops_prometheus_replica", "label": "glueops_prometheus_replica", "query": { "query": "label_values(__replica__)" } },
   { "name": "DS_PROMETHEUS", "label": "Datasource", "query": "prometheus" },
   {
    "name": "pod",
    "label": "pod",
    "query": {
     "query": "label_values(kube_pod_info{pod=~\".*external-dns.*\"}, pod)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "External-dns endpoints",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Total external-dns registry endpoints",
   "type": "timeseries",
   "description": "Number of Endpoints in the registry",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "external_dns_registry_endpoints_total {captain_domain=\"$glueops_captain_domain\",__replica__=\"$glueops_prometheus_replica\",pod=~\".*external-dns.*\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Total external-dns source endpoints",
   "type": "timeseries",
   "description": "Number of Endpoints in all sources",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "external_dns_source_endpoints_total {captain_domain=\"$glueops_captain_domain\",__replica__=\"$glueops_prometheus_replica\",pod=~\".*external-dns.*\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "External-dns errors",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Total external-dns registry errors",
   "type": "timeseries",
   "description": "Number of Registry errors",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "external_dns_registry_errors_total {captain_domain=\"$glueops_captain_domain\",__replica__=\"$glueops_prometheus_replica\",pod=~\".*external-dns.*\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Total external-dns source errors",
   "type": "timeseries",
   "description": "Number of Source errors",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "external_dns_source_errors_total {captain_domain=\"$glueops_captain_domain\",__replica__=\"$glueops_prometheus_replica\",pod=~\".*external-dns.*\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "External-dns sync",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Timestamp of last successful sync with the DNS provider",
   "type": "bargauge",
   "description": "Timestamp of last successful sync with the DNS provider",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsLocal" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1000 * (external_dns_controller_last_sync_timestamp_seconds{captain_domain=\"$glueops_captain_domain\",__replica__=\"$glueops_prometheus_replica\",pod=~\".*external-dns.*\",pod=~\"$pod\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "External-dns pods",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{captain_domain=\"$glueops_captain_domain\",__replica__=\"$glueops_prometheus_replica\",pod=~\".*external-dns.*\",pod=~\"$pod\"}) by (pod)",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "scalar(kube_resourcequota{captain_domain=\"$glueops_captain_domain\",__replica__=\"$glueops_prometheus_replica\",pod=~\".*external-dns.*\",pod=~\"$pod\", type=\"hard\",resource=\"requests.cpu\"})",
     "legendFormat": "quota - requests"
    },
    {
     "expr": "scalar(kube_resourcequota{captain_domain=\"$glueops_captain_domain\",__replica__=\"$glueops_prometheus_replica\",pod=~\".*external-dns.*\",pod=~\"$pod\", type=\"hard\",resource=\"limits.cpu\"})",
     "legendFormat": "quota - limits"
    }
   ]
  },
  {
   "title": "Memory Usage (w/o cache)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{captain_domain=\"$glueops_captain_domain\",__replica__=\"$glueops_prometheus_replica\",pod=~\".*external-dns.*\",pod=~\"$pod\",container!=\"\", image!=\"\"}) by (pod)",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "scalar(kube_resourcequota{captain_domain=\"$glueops_captain_domain\",__replica__=\"$glueops_prometheus_replica\",pod=~\".*external-dns.*\", type=\"hard\",resource=\"requests.memory\"})",
     "legendFormat": "quota - requests"
    },
    {
     "expr": "scalar(kube_resourcequota{captain_domain=\"$glueops_captain_domain\",__replica__=\"$glueops_prometheus_replica\",pod=~\".*external-dns.*\",pod=~\"$pod\",type=\"hard\",resource=\"limits.memory\"})",
     "legendFormat": "quota - limits"
    }
   ]
  },
  {
   "title": "CPU Quota",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{captain_domain=\"$glueops_captain_domain\",__replica__=\"$glueops_prometheus_replica\",pod=~\".*external-dns.*\",pod=~\"$pod\"}) by (pod)"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{captain_domain=\"$glueops_captain_domain\",__replica__=\"$glueops_prometheus_replica\",pod=~\".*external-dns.*\",pod=~\"$pod\",resource=\"cpu\"}) by (pod)"
    },
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{captain_domain=\"$glueops_captain_domain\",__replica__=\"$glueops_prometheus_replica\",pod=~\".*external-dns.*\",pod=~\"$pod\"}) by (pod) / sum(kube_pod_container_resource_requests{captain_domain=\"$glueops_captain_domain\",__replica__=\"$glueops_prometheus_replica\",pod=~\".*external-dns.*\",pod=~\"$pod\",resource=\"cpu\"}) by (pod)"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{captain_domain=\"$glueops_captain_domain\",__replica__=\"$glueops_prometheus_replica\",pod=~\".*external-dns.*\",pod=~\"$pod\",resource=\"cpu\"}) by (pod)"
    },
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{captain_domain=\"$glueops_captain_domain\",__replica__=\"$glueops_prometheus_replica\",pod=~\".*external-dns.*\",pod=~\"$pod\"}) by (pod) / sum(kube_pod_container_resource_limits{captain_domain=\"$glueops_captain_domain\",__replica__=\"$glueops_prometheus_replica\",pod=~\".*external-dns.*\",pod=~\"$pod\",resource=\"cpu\"}) by (pod)"
    }
   ]
  },
  {
   "title": "Memory Quota",
   "type": "table-old",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{captain_domain=\"$glueops_captain_domain\",__replica__=\"$glueops_prometheus_replica\",pod=~\".*external-dns.*\",pod=~\"$pod\",container!=\"\", image!=\"\"}) by (pod)"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{captain_domain=\"$glueops_captain_domain\",__replica__=\"$glueops_prometheus_replica\",pod=~\".*external-dns.*\",pod=~\"$pod\",resource=\"memory\"}) by (pod)"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{captain_domain=\"$glueops_captain_domain\",__replica__=\"$glueops_prometheus_replica\",pod=~\".*external-dns.*\",pod=~\"$pod\",container!=\"\", image!=\"\"}) by (pod) / sum(kube_pod_container_resource_requests{captain_domain=\"$glueops_captain_domain\",__replica__=\"$glueops_prometheus_replica\",pod=~\".*external-dns.*\",pod=~\"$pod\",resource=\"memory\"}) by (pod)"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{captain_domain=\"$glueops_captain_domain\",__replica__=\"$glueops_prometheus_replica\",pod=~\".*external-dns.*\",pod=~\"$pod\", resource=\"memory\"}) by (pod)"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{captain_domain=\"$glueops_captain_domain\",__replica__=\"$glueops_prometheus_replica\",pod=~\".*external-dns.*\",pod=~\"$pod\",container!=\"\", image!=\"\"}) by (pod) / sum(kube_pod_container_resource_limits{captain_domain=\"$glueops_captain_domain\",__replica__=\"$glueops_prometheus_replica\",pod=~\".*external-dns.*\",pod=~\"$pod\",resource=\"memory\"}) by (pod)"
    },
    {
     "expr": "sum(container_memory_rss{captain_domain=\"$glueops_captain_domain\",__replica__=\"$glueops_prometheus_replica\",pod=~\".*external-dns.*\",pod=~\"$pod\",container!=\"\"}) by (pod)"
    },
    {
     "expr": "sum(container_memory_cache{captain_domain=\"$glueops_captain_domain\",__replica__=\"$glueops_prometheus_replica\",pod=~\".*external-dns.*\",pod=~\"$pod\",container!=\"\"}) by (pod)"
    },
    {
     "expr": "sum(container_memory_swap{captain_domain=\"$glueops_captain_domain\",__replica__=\"$glueops_prometheus_replica\",pod=~\".*external-dns.*\",pod=~\"$pod\",container!=\"\"}) by (pod)"
    }
   ]
  }
 ]
}